<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="images\background.jpg" />
    <None Remove="images\slotmachine.png" />
    <None Remove="images\Symbol01.png" />
    <None Remove="images\Symbol02.png" />
    <None Remove="images\Symbol03.png" />
    <None Remove="images\Symbol04.png" />
    <None Remove="images\Symbol05.png" />
    <None Remove="images\Symbol06.png" />
    <None Remove="images\Symbol07.png" />
    <None Remove="images\Symbol08.png" />
    <None Remove="images\Symbol09.png" />
    <None Remove="images\Symbol10.png" />
    <None Remove="images\Symbol11.png" />
    <None Remove="images\Symbol12.png" />
    <None Remove="images\Symbol13.png" />
    <None Remove="images\Symbol14.png" />
    <None Remove="images\Symbol15.png" />
    <None Remove="images\Symbol16.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="images\Symbol02.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="images\background.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\slotmachine.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Symbol01.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Symbol03.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Symbol04.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Symbol05.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Symbol06.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Symbol07.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Symbol08.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Symbol09.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Symbol10.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Symbol11.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Symbol12.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Symbol13.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Symbol14.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Symbol15.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\Symbol16.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
